import { CPU, Motherboard, RAM, GPU, Storage, PSU, Case, Cooler } from '@/types/parts';

// CPUs
export const CPUS: CPU[] = [
  {
    id: 'cpu-1',
    name: 'AMD Ryzen 7 9800X3D',
    brand: 'AMD',
    price: { eur: 519, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseGHz: 4.7,
    boostGHz: 5.2,
    tdpW: 120,
    gen: 'Zen 5',
    has3DCache: true,
    badges: [{ label: 'TOP Gaming', tone: 'success' }],
  },
  {
    id: 'cpu-2',
    name: 'AMD Ryzen 9 9950X',
    brand: 'AMD',
    price: { eur: 689, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    cores: 16,
    threads: 32,
    baseGHz: 4.3,
    boostGHz: 5.7,
    tdpW: 170,
    gen: 'Zen 5',
    badges: [{ label: 'Multi-Core', tone: 'info' }],
  },
  {
    id: 'cpu-3',
    name: 'AMD Ryzen 5 9600X',
    brand: 'AMD',
    price: { eur: 219, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    cores: 6,
    threads: 12,
    baseGHz: 3.9,
    boostGHz: 5.4,
    tdpW: 65,
    gen: 'Zen 5',
    badges: [{ label: 'Nueva Gen', tone: 'info' }],
  },
  {
    id: 'cpu-4',
    name: 'AMD Ryzen 7 9700X',
    brand: 'AMD',
    price: { eur: 298, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseGHz: 3.8,
    boostGHz: 5.5,
    tdpW: 65,
    gen: 'Zen 5',
  },
  {
    id: 'cpu-5',
    name: 'Intel Core i7-14700KF',
    brand: 'Intel',
    price: { eur: 340, isOrientative: true },
    stock: 'in_stock',
    socket: 'LGA1700',
    cores: 20,
    threads: 28,
    baseGHz: 3.4,
    boostGHz: 5.6,
    tdpW: 125,
    gen: 'Raptor Lake',
  },
  {
    id: 'cpu-6',
    name: 'AMD Ryzen 5 7600X',
    brand: 'AMD',
    price: { eur: 179, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    cores: 6,
    threads: 12,
    baseGHz: 4.7,
    boostGHz: 5.3,
    tdpW: 105,
    gen: 'Zen 4',
    badges: [{ label: 'Mejor relación', tone: 'info' }],
  },
  {
    id: 'cpu-7',
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    price: { eur: 399, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseGHz: 4.2,
    boostGHz: 5.0,
    tdpW: 120,
    gen: 'Zen 4',
    has3DCache: true,
    badges: [{ label: 'TOP Gaming', tone: 'success' }],
  },
  {
    id: 'cpu-8',
    name: 'AMD Ryzen 7 5700X',
    brand: 'AMD',
    price: { eur: 152, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM4',
    cores: 8,
    threads: 16,
    baseGHz: 3.4,
    boostGHz: 4.6,
    tdpW: 65,
    gen: 'Zen 3',
  },
];

// Placas Base
export const MOTHERBOARDS: Motherboard[] = [
  {
    id: 'mb-1',
    name: 'ASUS PRIME B650-PLUS WIFI',
    brand: 'ASUS',
    price: { eur: 157, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    socket: 'AM5',
    chipset: 'B650',
    ramGen: 'DDR5',
    ramMaxMHz: 6400,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 4,
    wifi: 'WiFi 6',
    usbC: true,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'mb-2',
    name: 'MSI PRO B650-S WIFI',
    brand: 'MSI',
    price: { eur: 153, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    chipset: 'B650',
    ramGen: 'DDR5',
    ramMaxMHz: 6400,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 4,
    wifi: 'WiFi 6',
    usbC: true,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'mb-3',
    name: 'MSI MAG B650 TOMAHAWK WIFI',
    brand: 'MSI',
    price: { eur: 179, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    chipset: 'B650',
    ramGen: 'DDR5',
    ramMaxMHz: 6400,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 4,
    wifi: 'WiFi 6',
    usbC: true,
  },
  {
    id: 'mb-4',
    name: 'ASUS PRIME B760-PLUS',
    brand: 'ASUS',
    price: { eur: 126, isOrientative: true },
    stock: 'in_stock',
    socket: 'LGA1700',
    chipset: 'B760',
    ramGen: 'DDR5',
    ramMaxMHz: 5600,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 4,
    wifi: 'WiFi 6',
    usbC: true,
  },
  {
    id: 'mb-5',
    name: 'MSI B850 GAMING PLUS WIFI',
    brand: 'MSI',
    price: { eur: 207, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    chipset: 'B850',
    ramGen: 'DDR5',
    ramMaxMHz: 7200,
    m2SlotsGen: [5, 4],
    pcieX16Gen: 5,
    wifi: 'WiFi 6E',
    usbC: true,
  },
  {
    id: 'mb-6',
    name: 'ASUS TUF GAMING B650-PLUS WIFI',
    brand: 'ASUS',
    price: { eur: 181, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM5',
    chipset: 'B650',
    ramGen: 'DDR5',
    ramMaxMHz: 6400,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 4,
    wifi: 'WiFi 6',
    usbC: true,
  },
  {
    id: 'mb-7',
    name: 'ASUS PRIME Z790-P WIFI',
    brand: 'ASUS',
    price: { eur: 217, isOrientative: true },
    stock: 'in_stock',
    socket: 'LGA1700',
    chipset: 'Z790',
    ramGen: 'DDR5',
    ramMaxMHz: 7200,
    m2SlotsGen: [4, 4],
    pcieX16Gen: 5,
    wifi: 'WiFi 6',
    usbC: true,
  },
  {
    id: 'mb-8',
    name: 'Gigabyte B550M K Rev. 1.0',
    brand: 'Gigabyte',
    price: { eur: 75, isOrientative: true },
    stock: 'in_stock',
    socket: 'AM4',
    chipset: 'B550',
    ramGen: 'DDR4',
    ramMaxMHz: 3600,
    m2SlotsGen: [4, 3],
    pcieX16Gen: 4,
    wifi: undefined,
    usbC: false,
  },
];

// RAM
export const RAMS: RAM[] = [
  {
    id: 'ram-1',
    name: 'Corsair Vengeance RGB DDR5 6000MHz 32GB',
    brand: 'Corsair',
    price: { eur: 163, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR5',
    mhz: 6000,
    cl: 30,
    expoXmp: 'EXPO|XMP',
    rgb: true,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'ram-2',
    name: 'Kingston FURY Beast DDR4 3200MHz 16GB',
    brand: 'Kingston',
    price: { eur: 69, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 16,
    kit: '2x8GB',
    ramGen: 'DDR4',
    mhz: 3200,
    cl: 16,
    expoXmp: 'XMP',
    rgb: false,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'ram-3',
    name: 'Forgeon Cyclone PLUS V2 DDR4 3200MHz 32GB',
    brand: 'Forgeon',
    price: { eur: 89, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR4',
    mhz: 3200,
    cl: 16,
    expoXmp: 'XMP',
    rgb: false,
  },
  {
    id: 'ram-4',
    name: 'Kingston FURY Beast DDR5 5600MHz 32GB',
    brand: 'Kingston',
    price: { eur: 126, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR5',
    mhz: 5600,
    cl: 36,
    expoXmp: 'EXPO|XMP',
    rgb: false,
  },
  {
    id: 'ram-5',
    name: 'Acer Predator Pallas II DDR5 6000MHz 32GB',
    brand: 'Acer',
    price: { eur: 159, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR5',
    mhz: 6000,
    cl: 34,
    expoXmp: 'EXPO|XMP',
    rgb: false,
  },
  {
    id: 'ram-6',
    name: 'Forgeon Cyclone PLUS V2 DDR4 3200MHz 16GB',
    brand: 'Forgeon',
    price: { eur: 50, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 16,
    kit: '2x8GB',
    ramGen: 'DDR4',
    mhz: 3200,
    cl: 16,
    expoXmp: 'XMP',
    rgb: false,
  },
  {
    id: 'ram-7',
    name: 'Corsair Vengeance DDR5 6000MHz 32GB',
    brand: 'Corsair',
    price: { eur: 130, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR5',
    mhz: 6000,
    cl: 36,
    expoXmp: 'EXPO|XMP',
    rgb: false,
  },
  {
    id: 'ram-8',
    name: 'Biwin Black Opal DW100 DDR5 RGB 6000MHz 32GB',
    brand: 'Biwin',
    price: { eur: 131, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR5',
    mhz: 6000,
    cl: 30,
    expoXmp: 'EXPO|XMP',
    rgb: true,
  },
  {
    id: 'ram-9',
    name: 'Crucial SO-DIMM DDR4 3200MHz 16GB',
    brand: 'Crucial',
    price: { eur: 67, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 16,
    kit: '1x16GB',
    ramGen: 'DDR4',
    mhz: 3200,
    cl: 22,
    expoXmp: 'XMP',
    rgb: false,
  },
  {
    id: 'ram-10',
    name: 'Adata XPG GAMMIX D35 DDR4 3200MHz 32GB',
    brand: 'Adata',
    price: { eur: 84, isOrientative: true },
    stock: 'in_stock',
    capacityGB: 32,
    kit: '2x16GB',
    ramGen: 'DDR4',
    mhz: 3200,
    cl: 16,
    expoXmp: 'XMP',
    rgb: false,
  },
];

// GPUs
export const GPUS: GPU[] = [
  {
    id: 'gpu-1',
    name: 'MSI GeForce RTX 5070 Ti VENTUS 3X OC 16GB',
    brand: 'MSI',
    price: { eur: 1018, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    vramGB: 16,
    pcieGen: 5,
    lengthMM: 336,
    tgpW: 260, // Actualizado con datos reales
    badges: [{ label: 'Trending', tone: 'success' }, { label: '1440p/4K', tone: 'info' }],
  },
  {
    id: 'gpu-2',
    name: 'MSI GeForce RTX 5070 VENTUS 2X OC 12GB',
    brand: 'MSI',
    price: { eur: 628, isOrientative: true },
    stock: 'in_stock',
    vramGB: 12,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 220, // Actualizado con datos reales
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'gpu-3',
    name: 'ASUS DUAL GeForce RTX 5060 Ti OC Edition 16GB',
    brand: 'ASUS',
    price: { eur: 485, isOrientative: true },
    stock: 'in_stock',
    vramGB: 16,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 190,
  },
  {
    id: 'gpu-4',
    name: 'MSI GeForce RTX 5060 Ti VENTUS 2X OC PLUS 16GB',
    brand: 'MSI',
    price: { eur: 449, isOrientative: true },
    stock: 'in_stock',
    vramGB: 16,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 190,
  },
  {
    id: 'gpu-5',
    name: 'MSI GeForce RTX 5080 VENTUS 3X OC PLUS 16GB',
    brand: 'MSI',
    price: { eur: 1300, isOrientative: true },
    stock: 'in_stock',
    vramGB: 16,
    pcieGen: 5,
    lengthMM: 336,
    tgpW: 350, // Actualizado con datos reales
  },
  {
    id: 'gpu-6',
    name: 'MSI GeForce RTX 5060 Ti VENTUS 2X OC PLUS 8GB',
    brand: 'MSI',
    price: { eur: 405, isOrientative: true },
    stock: 'in_stock',
    vramGB: 8,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 170,
  },
  {
    id: 'gpu-7',
    name: 'MSI GeForce RTX 5060 VENTUS 2X OC 8GB',
    brand: 'MSI',
    price: { eur: 299, isOrientative: true },
    stock: 'in_stock',
    vramGB: 8,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 150, // Actualizado con datos reales
  },
  {
    id: 'gpu-8',
    name: 'ASUS Dual GeForce RTX 5060 OC Edition 8GB',
    brand: 'ASUS',
    price: { eur: 304, isOrientative: true },
    stock: 'in_stock',
    vramGB: 8,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 150, // Actualizado con datos reales
  },
  {
    id: 'gpu-9',
    name: 'ASUS PRIME GeForce RTX 5060 Ti OC Edition 16GB',
    brand: 'ASUS',
    price: { eur: 499, isOrientative: true },
    stock: 'in_stock',
    vramGB: 16,
    pcieGen: 5,
    lengthMM: 243,
    tgpW: 190,
  },
  {
    id: 'gpu-10',
    name: 'Gigabyte Radeon RX 7600 GAMING OC 8GB',
    brand: 'Gigabyte',
    price: { eur: 249, isOrientative: true },
    stock: 'in_stock',
    vramGB: 8,
    pcieGen: 4,
    lengthMM: 243,
    tgpW: 165,
  },
];

// Almacenamiento
export const STORAGES: Storage[] = [
  {
    id: 'storage-1',
    name: 'Kingston NV3 1TB Disco SSD',
    brand: 'Kingston',
    price: { eur: 60, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    type: 'NVME',
    capacityTB: 1,
    readMBs: 6000,
    writeMBs: 5000,
    pcieGen: 4,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'storage-2',
    name: 'Toshiba Canvio Basics 2TB Disco Externo Portátil USB 3.2',
    brand: 'Toshiba',
    price: { eur: 69, isOrientative: true },
    stock: 'in_stock',
    type: 'SATA',
    capacityTB: 2,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'storage-3',
    name: 'Toshiba Canvio Basics 1TB Disco Externo Portátil USB 3.2',
    brand: 'Toshiba',
    price: { eur: 50, isOrientative: true },
    stock: 'in_stock',
    type: 'SATA',
    capacityTB: 1,
  },
  {
    id: 'storage-4',
    name: 'Forgeon Nimbus PRO Disco SSD 1TB',
    brand: 'Forgeon',
    price: { eur: 79, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 1,
    readMBs: 7400,
    writeMBs: 7000,
    pcieGen: 4,
  },
  {
    id: 'storage-5',
    name: 'Samsung 990 Pro 2TB Disco SSD',
    brand: 'Samsung',
    price: { eur: 163, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 2,
    readMBs: 7450,
    writeMBs: 6900,
    pcieGen: 4,
  },
  {
    id: 'storage-6',
    name: 'Samsung 990 EVO Plus 1TB Disco SSD',
    brand: 'Samsung',
    price: { eur: 84, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 1,
    readMBs: 7150,
    writeMBs: 6800,
    pcieGen: 4,
  },
  {
    id: 'storage-7',
    name: 'Samsung 990 EVO Plus 2TB Disco SSD',
    brand: 'Samsung',
    price: { eur: 130, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 2,
    readMBs: 7250,
    writeMBs: 7000,
    pcieGen: 5,
  },
  {
    id: 'storage-8',
    name: 'Forgeon Nimbus PRO Disco SSD 2TB',
    brand: 'Forgeon',
    price: { eur: 144, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 2,
    readMBs: 7400,
    writeMBs: 7000,
    pcieGen: 4,
  },
  {
    id: 'storage-9',
    name: 'Toshiba Canvio Basics 4TB Disco Externo Portátil USB 3.2',
    brand: 'Toshiba',
    price: { eur: 101, isOrientative: true },
    stock: 'in_stock',
    type: 'SATA',
    capacityTB: 4,
  },
  {
    id: 'storage-10',
    name: 'WD BLACK SN7100 2TB Disco SSD',
    brand: 'Western Digital',
    price: { eur: 120, isOrientative: true },
    stock: 'in_stock',
    type: 'NVME',
    capacityTB: 2,
    readMBs: 7250,
    writeMBs: 7000,
    pcieGen: 4,
  },
];

// Fuentes
export const PSUS: PSU[] = [
  {
    id: 'psu-1',
    name: 'MSI MAG A650BN 650W 80 Plus Bronze',
    brand: 'MSI',
    price: { eur: 58, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    watts: 650,
    standard: 'ATX 3.0',
    efficiency80: 'Gold',
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'psu-2',
    name: 'Corsair CX750 750 W 80 Plus Bronze',
    brand: 'Corsair',
    price: { eur: 73, isOrientative: true },
    stock: 'in_stock',
    watts: 750,
    standard: 'ATX 3.0',
    efficiency80: 'Gold',
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'psu-3',
    name: 'Corsair RMe Series RM850e ATX 3.1 PCIe 5.1 850W',
    brand: 'Corsair',
    price: { eur: 127, isOrientative: true },
    stock: 'in_stock',
    watts: 850,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-4',
    name: 'MSI MAG A850GL PCIES II ATX 3.1 850W 80 Plus Gold',
    brand: 'MSI',
    price: { eur: 98, isOrientative: true },
    stock: 'in_stock',
    watts: 850,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-5',
    name: 'MSI MAG A750GL PCIES II ATX 3.1 750W 80 Plus Gold',
    brand: 'MSI',
    price: { eur: 85, isOrientative: true },
    stock: 'in_stock',
    watts: 750,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-6',
    name: 'Corsair RMe Series RM750e ATX 3.1 PCIe 5.1 750W',
    brand: 'Corsair',
    price: { eur: 120, isOrientative: true },
    stock: 'in_stock',
    watts: 750,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-7',
    name: 'Tempest PSU 750W Fuente de Alimentación',
    brand: 'Tempest',
    price: { eur: 34, isOrientative: true },
    stock: 'in_stock',
    watts: 750,
    standard: 'ATX 3.0',
    efficiency80: 'Gold',
  },
  {
    id: 'psu-8',
    name: 'Corsair RMe Series RM1000e ATX 3.1 PCIe 5.1 1000W',
    brand: 'Corsair',
    price: { eur: 172, isOrientative: true },
    stock: 'in_stock',
    watts: 1000,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-9',
    name: 'MSI MAG A850GL PCIE5 850W 80 PLUS Gold',
    brand: 'MSI',
    price: { eur: 106, isOrientative: true },
    stock: 'in_stock',
    watts: 850,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
  {
    id: 'psu-10',
    name: 'MSI MPG A850G PCIE5 850W 80 Plus Gold Full Modular',
    brand: 'MSI',
    price: { eur: 119, isOrientative: true },
    stock: 'in_stock',
    watts: 850,
    standard: 'ATX 3.1',
    pcie5_12vhpwr: true,
    efficiency80: 'Gold',
  },
];

// Cajas
export const CASES: Case[] = [
  {
    id: 'case-1',
    name: 'Tempest Umbra RGB Torre ATX Negra',
    brand: 'Tempest',
    price: { eur: 59, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    maxGpuLenMM: 350,
    supports360Rad: true,
    fansIncluded: 3,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'case-2',
    name: 'MSI MAG FORGE 121A AIRFLOW ARGB Semi Torre ATX',
    brand: 'MSI',
    price: { eur: 49, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 320,
    supports360Rad: false,
    fansIncluded: 3,
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'case-3',
    name: 'MSI MAG FORGE M100R Cristal Templado USB 3.2 ARGB',
    brand: 'MSI',
    price: { eur: 54, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 330,
    supports360Rad: false,
    fansIncluded: 3,
  },
  {
    id: 'case-4',
    name: 'Tempest Umbra RGB Torre ATX Blanca',
    brand: 'Tempest',
    price: { eur: 59, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 350,
    supports360Rad: true,
    fansIncluded: 3,
  },
  {
    id: 'case-5',
    name: 'Forgeon Mithril ARGB Mesh Torre ATX Negra',
    brand: 'Forgeon',
    price: { eur: 119, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 400,
    supports360Rad: true,
    fansIncluded: 4,
  },
  {
    id: 'case-6',
    name: 'Forgeon Arcanite ARGB Mesh Torre ATX Negra',
    brand: 'Forgeon',
    price: { eur: 124, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 400,
    supports360Rad: true,
    fansIncluded: 4,
  },
  {
    id: 'case-7',
    name: 'MSI MAG FORGE 320R AIRFLOW Cristal Templado USB 3.2',
    brand: 'MSI',
    price: { eur: 79, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 360,
    supports360Rad: true,
    fansIncluded: 3,
  },
  {
    id: 'case-8',
    name: 'Nox Hummer Quantum Cristal Templado USB 3.0 ARGB',
    brand: 'Nox',
    price: { eur: 74, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 350,
    supports360Rad: true,
    fansIncluded: 3,
  },
  {
    id: 'case-9',
    name: 'MSI MAG PANO 100R PZ ARGB Semi Torre Doble Cristal Templado USB-C Blanca',
    brand: 'MSI',
    price: { eur: 126, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 360,
    supports360Rad: true,
    fansIncluded: 4,
  },
  {
    id: 'case-10',
    name: 'MSI MAG FORGE M100R Semi Torre mATX Cristal Templado USB 3.2 ARGB Blanca',
    brand: 'MSI',
    price: { eur: 47, isOrientative: true },
    stock: 'in_stock',
    maxGpuLenMM: 320,
    supports360Rad: false,
    fansIncluded: 3,
  },
];

// Refrigeración
export const COOLERS: Cooler[] = [
  {
    id: 'cooler-1',
    name: 'Corsair NAUTILUS 240 RS ARGB Kit Refrigeración Líquida 240mm',
    brand: 'Corsair',
    price: { eur: 114, isOrientative: true },
    stock: 'in_stock',
    recommended: true,
    type: 'AIO',
    radMM: 240,
    tdpSupportW: 200,
    compatibleSockets: ['AM5', 'LGA1700', 'LGA1851'],
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'cooler-2',
    name: 'Tempest Iceflow Refrigeración Líquida 240 ARGB Kit',
    brand: 'Tempest',
    price: { eur: 44, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 240,
    tdpSupportW: 180,
    compatibleSockets: ['AM5', 'LGA1700'],
  },
  {
    id: 'cooler-3',
    name: 'Corsair NAUTILUS 360 RS ARGB Kit Refrigeración Líquida 360mm',
    brand: 'Corsair',
    price: { eur: 139, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 250,
    compatibleSockets: ['AM5', 'LGA1700', 'LGA1851'],
    badges: [{ label: 'Trending', tone: 'success' }],
  },
  {
    id: 'cooler-4',
    name: 'Corsair NAUTILUS 360 RS Refrigeración Líquida 360mm',
    brand: 'Corsair',
    price: { eur: 124, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 250,
    compatibleSockets: ['AM5', 'LGA1700', 'LGA1851'],
  },
  {
    id: 'cooler-5',
    name: 'Tempest Liquid Cooler 360 Kit de Refrigeración Líquida',
    brand: 'Tempest',
    price: { eur: 59, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 200,
    compatibleSockets: ['AM5', 'LGA1700'],
  },
  {
    id: 'cooler-6',
    name: 'Nfortec ATRIA X Kit de Refrigeración Líquida 360mm',
    brand: 'Nfortec',
    price: { eur: 96, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 220,
    compatibleSockets: ['AM5', 'LGA1700'],
  },
  {
    id: 'cooler-7',
    name: 'Corsair NAUTILUS 360 RS ARGB Kit Refrigeración Líquida 360mm Blanco',
    brand: 'Corsair',
    price: { eur: 139, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 250,
    compatibleSockets: ['AM5', 'LGA1700', 'LGA1851'],
  },
  {
    id: 'cooler-8',
    name: 'Corsair NAUTILUS 240 RS Kit Refrigeración Líquida 240mm',
    brand: 'Corsair',
    price: { eur: 104, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 240,
    tdpSupportW: 200,
    compatibleSockets: ['AM5', 'LGA1700', 'LGA1851'],
  },
  {
    id: 'cooler-9',
    name: 'Tempest Liquid Cooler 360 ARGB Kit de Refrigeración Líquida 360mm',
    brand: 'Tempest',
    price: { eur: 79, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 200,
    compatibleSockets: ['AM5', 'LGA1700'],
  },
  {
    id: 'cooler-10',
    name: 'Tempest Liquid Cooler 360 Kit de Refrigeración Líquida Blanco',
    brand: 'Tempest',
    price: { eur: 64, isOrientative: true },
    stock: 'in_stock',
    type: 'AIO',
    radMM: 360,
    tdpSupportW: 200,
    compatibleSockets: ['AM5', 'LGA1700'],
  },
];

// Helper para obtener partes por categoría
export function getPartsByCategory(category: string): any[] {
  switch (category) {
    case 'cpu': return CPUS;
    case 'mb': return MOTHERBOARDS;
    case 'ram': return RAMS;
    case 'gpu': return GPUS;
    case 'storage': return STORAGES;
    case 'psu': return PSUS;
    case 'case': return CASES;
    case 'cooler': return COOLERS;
    default: return [];
  }
}

export function getPartById(id: string): any | null {
  const all = [...CPUS, ...MOTHERBOARDS, ...RAMS, ...GPUS, ...STORAGES, ...PSUS, ...CASES, ...COOLERS];
  return all.find(p => p.id === id) || null;
}

